# Do not edit. This file is automatically generated from official documentation
# on the web by https://github.com/osteele/html2cheatsheet.
# Documentation source: https://support.apple.com/guide/final-cut-pro/keyboard-shortcuts-ver90ba5929/mac

cheatsheet do
  title 'Final Cut Pro'
  docset_file_name 'Final_Cut_Pro'
  keyword 'fcp'
  source_url 'http://cheat.kapeli.com'

  category do
    id 'Application'
    entry do
      name 'Hide Application'
      command 'CMD+H'
      notes 'Hide Final Cut Pro'
    end
    entry do
      name 'Hide Other Applications'
      command 'CMD+OPTION+H'
      notes 'Hide all applications except Final Cut Pro'
    end
    entry do
      name 'Keyboard Customization'
      command 'CMD+OPTION+K'
      notes 'Open the Command Editor'
    end
    entry do
      name 'Minimize'
      command 'CMD+M'
      notes 'Minimize Final Cut Pro'
    end
    entry do
      name 'Open Library'
      command 'CMD+O'
      notes 'Open an existing library or a new library'
    end
    entry do
      name 'Preferences'
      command 'CMD+,'
      notes 'Open the Final Cut Pro Preferences window'
    end
    entry do
      name 'Quit'
      command 'CMD+Q'
      notes 'Quit Final Cut Pro'
    end
    entry do
      name 'Redo Change'
      command 'CMD+SHIFT+Z'
      notes 'Redo the last command'
    end
    entry do
      name 'Undo Change'
      command 'CMD+Z'
      notes 'Undo the last command'
    end
  end

  category do
    id 'Editing'
    entry do
      name 'Adjust Volume Absolute'
      command 'CTRL+OPTION+L'
      notes 'Adjust the audio volume across all selected clips to a specific dB value'
    end
    entry do
      name 'Adjust Volume Relative'
      command 'CTRL+L'
      notes 'Adjust the audio volume across all selected clips by the same dB value'
    end
    entry do
      name 'Append to Storyline'
      command 'E'
      notes 'Add the selection to the end of the storyline'
    end
    entry do
      name 'Audition: Add to Audition'
      command 'CTRL+SHIFT+Y'
      notes 'Add the selected clip to the audition'
    end
    entry do
      name 'Audition: Duplicate as Audition'
      command 'OPTION+Y'
      notes 'Create an audition with a timeline clip and a duplicate version of the clip, including applied effects'
    end
    entry do
      name 'Audition: Duplicate from Original'
      command 'CMD+SHIFT+Y'
      notes 'Duplicate the selected audition clip without applied effects'
    end
    entry do
      name 'Audition: Replace and Add to Audition'
      command 'SHIFT+Y'
      notes 'Create an audition and replace the timeline clip with the current selection'
    end
    entry do
      name 'Blade'
      command 'CMD+B'
      notes 'Cut the primary storyline clip (or the selection) at the skimmer or playhead location'
    end
    entry do
      name 'Blade All'
      command 'CMD+SHIFT+B'
      notes 'Cut all clips at the skimmer or playhead location'
    end
    entry do
      name 'Break Apart Clip Items'
      command 'CMD+SHIFT+G'
      notes 'Break the selected item into its component parts'
    end
    entry do
      name 'Change Duration'
      command 'CTRL+D'
      notes 'Change the duration of the selection'
    end
    entry do
      name 'Connect Default Lower Third'
      command 'CTRL+SHIFT+T'
      notes 'Connect the default lower third to the primary storyline'
    end
    entry do
      name 'Connect Default Title'
      command 'CTRL+T'
      notes 'Connect the default title to the primary storyline'
    end
    entry do
      name 'Connect to Primary Storyline'
      command 'Q'
      notes 'Connect the selection to the primary storyline'
    end
    entry do
      name 'Connect to Primary Storyline - Backtimed'
      command 'SHIFT+Q'
      notes 'Connect the selection to the primary storyline, aligning the selection’s end point with the skimmer or playhead'
    end
    entry do
      name 'Create Audition'
      command 'CMD+Y'
      notes 'Create an audition from the selection'
    end
    entry do
      name 'Create Storyline'
      command 'CMD+G'
      notes 'Create a storyline from a selection of connected clips'
    end
    entry do
      name 'Cut and Switch to Viewer Angle 1'
      command '1'
      notes 'Cut and switch the multicam clip to angle 1 of the current bank'
    end
    entry do
      name 'Cut and Switch to Viewer Angle 2'
      command '2'
      notes 'Cut and switch the multicam clip to angle 2 of the current bank'
    end
    entry do
      name 'Cut and Switch to Viewer Angle 3'
      command '3'
      notes 'Cut and switch the multicam clip to angle 3 of the current bank'
    end
    entry do
      name 'Cut and Switch to Viewer Angle 4'
      command '4'
      notes 'Cut and switch the multicam clip to angle 4 of the current bank'
    end
    entry do
      name 'Cut and Switch to Viewer Angle 5'
      command '5'
      notes 'Cut and switch the multicam clip to angle 5 of the current bank'
    end
    entry do
      name 'Cut and Switch to Viewer Angle 6'
      command '6'
      notes 'Cut and switch the multicam clip to angle 6 of the current bank'
    end
    entry do
      name 'Cut and Switch to Viewer Angle 7'
      command '7'
      notes 'Cut and switch the multicam clip to angle 7 of the current bank'
    end
    entry do
      name 'Cut and Switch to Viewer Angle 8'
      command '8'
      notes 'Cut and switch the multicam clip to angle 8 of the current bank'
    end
    entry do
      name 'Cut and Switch to Viewer Angle 9'
      command '9'
      notes 'Cut and switch the multicam clip to angle 9 of the current bank'
    end
    entry do
      name 'Delete'
      command 'Delete'
      notes 'Delete the timeline selection, reject the browser selection, or remove a through edit'
    end
    entry do
      name 'Delete Selection Only'
      command 'CMD+OPTION+Delete'
      notes 'Delete the selection and attach the connected clip or clips to the resulting gap clip'
    end
    entry do
      name 'Deselect All'
      command 'CMD+SHIFT+A'
      notes 'Deselect all selected items'
    end
    entry do
      name 'Duplicate'
      command 'CMD+D'
      notes 'Duplicate the browser selection'
    end
    entry do
      name 'Enable/Disable Clip'
      command 'V'
      notes 'Enable or disable playback for the selection'
    end
    entry do
      name 'Expand Audio'
      command 'CTRL+S'
      notes 'View audio and video separately for selected clips'
    end
    entry do
      name 'Expand/Collapse Audio Components'
      command 'CTRL+OPTION+S'
      notes 'Expand or collapse audio components for the selection in the timeline'
    end
    entry do
      name 'Extend Edit'
      command 'SHIFT+X'
      notes 'Extend the selected edit point to the skimmer or playhead position'
    end
    entry do
      name 'Extend Selection Down'
      command 'SHIFT+Down Arrow'
      notes 'In the browser list view, add the next item to the selection'
    end
    entry do
      name 'Extend Selection to Next Clip'
      command 'CMD+CTRL+Right-Arrow'
      notes 'In the timeline, add the next item to the selection'
    end
    entry do
      name 'Extend Selection Up'
      command 'SHIFT+Up Arrow'
      notes 'In the browser list view, add the previous item to the selection'
    end
    entry do
      name 'Finalize Audition'
      command 'OPTION+SHIFT+Y'
      notes 'Dissolve the audition and replace it with the audition pick'
    end
    entry do
      name 'Insert'
      command 'W'
      notes 'Insert the selection at the skimmer or playhead position'
    end
    entry do
      name 'Insert/Connect Freeze Frame'
      command 'OPTION+F'
      notes 'Insert a freeze frame at the playhead or skimmer location in the timeline, or connect a freeze frame from the skimmer or playhead location in the event to the playhead location in the timeline'
    end
    entry do
      name 'Insert Gap'
      command 'OPTION+W'
      notes 'Insert a gap clip at the skimmer or playhead position'
    end
    entry do
      name 'Insert Default Generator'
      command 'CMD+OPTION+W'
      notes 'Insert the default generator at the skimmer or playhead position'
    end
    entry do
      name 'Lift from Storyline'
      command 'CMD+OPTION+Up Arrow'
      notes 'Lift the selection from the storyline and connect it to the resulting gap clips'
    end
    entry do
      name 'Lower Volume 1 dB'
      command 'CTRL+-'
      notes 'Lower the audio volume by 1 dB'
    end
    entry do
      name 'Move Playhead Position'
      command 'CTRL+P'
      notes 'Move the playhead by entering a timecode value'
    end
    entry do
      name 'New Compound Clip'
      command 'OPTION+G'
      notes 'Create a new compound clip (if there’s no selection, create an empty compound clip)'
    end
    entry do
      name 'Nudge Audio Subframe Left'
      command 'OPTION+,'
      notes 'Nudge the selected audio edit point left by one subframe, creating a split edit'
    end
    entry do
      name 'Nudge Audio Subframe Left Many'
      command 'OPTION+SHIFT+,'
      notes 'Nudge the selected audio edit point left by 10 subframes, creating a split edit'
    end
    entry do
      name 'Nudge Audio Subframe Right'
      command 'OPTION+.'
      notes 'Nudge the selected audio edit point right by one subframe, creating a split edit'
    end
    entry do
      name 'Nudge Audio Subframe Right Many'
      command 'OPTION+SHIFT+.'
      notes 'Nudge the selected audio edit point right by 10 subframes, creating a split edit'
    end
    entry do
      name 'Nudge Down'
      command 'OPTION+Down Arrow'
      notes 'Nudge down the value of the selected keyframe in the animation editor'
    end
    entry do
      name 'Nudge Left'
      command ','
      notes 'Nudge the selection one unit to the left'
    end
    entry do
      name 'Nudge Left Many'
      command 'SHIFT+,'
      notes 'Nudge the selection 10 units to the left'
    end
    entry do
      name 'Nudge Right'
      command '.'
      notes 'Nudge the selection one unit to the right'
    end
    entry do
      name 'Nudge Right Many'
      command 'SHIFT+.'
      notes 'Nudge the selection 10 units to the right'
    end
    entry do
      name 'Nudge Up'
      command 'OPTION+Up Arrow'
      notes 'Nudge up the value of the selected keyframe in the animation editor'
    end
    entry do
      name 'Open Audition'
      command 'Y'
      notes 'Open the selected audition'
    end
    entry do
      name 'Override Connections'
      command '`'
      notes 'Temporarily override clip connections for the selection'
    end
    entry do
      name 'Overwrite'
      command 'D'
      notes 'Overwrite at the skimmer or playhead position'
    end
    entry do
      name 'Overwrite - Backtimed'
      command 'SHIFT+D'
      notes 'Overwrite from the skimmer or playhead position back'
    end
    entry do
      name 'Overwrite to Primary Storyline'
      command 'CMD+OPTION+Down Arrow'
      notes 'Overwrite at the skimmer or playhead position in the primary storyline'
    end
    entry do
      name 'Paste as Connected'
      command 'OPTION+V'
      notes 'Paste the selection and connect it to the primary storyline'
    end
    entry do
      name 'Paste Insert at Playhead'
      command 'CMD+V'
      notes 'Insert the Clipboard contents at the skimmer or playhead position'
    end
    entry do
      name 'Previous Angle'
      command 'CTRL+SHIFT+Left Arrow'
      notes 'Switch to the previous angle in the multicam clip'
    end
    entry do
      name 'Previous Audio Angle'
      command 'OPTION+SHIFT+Left Arrow'
      notes 'Switch to the previous audio angle in the multicam clip'
    end
    entry do
      name 'Previous Pick'
      command 'CTRL+Left Arrow'
      notes 'Select the previous clip in the Audition window, making it the audition pick'
    end
    entry do
      name 'Previous Video Angle'
      command 'CMD+SHIFT+Left Arrow'
      notes 'Switch to the previous video angle in the multicam clip'
    end
    entry do
      name 'Raise Volume 1 dB'
      command 'CTRL+='
      notes 'Raise the audio volume by 1 dB'
    end
    entry do
      name 'Replace'
      command 'SHIFT+R'
      notes 'Replace the selected clip in the timeline with the browser selection'
    end
    entry do
      name 'Replace from Start'
      command 'OPTION+R'
      notes 'Replace the selected clip in the timeline with the browser selection, starting from its start point'
    end
    entry do
      name 'Replace with Gap'
      command 'SHIFT+Delete'
      notes 'Replace the selected timeline clip with a gap clip'
    end
    entry do
      name 'Select All'
      command 'CMD+A'
      notes 'Select all clips'
    end
    entry do
      name 'Select Clip'
      command 'C'
      notes 'Select the clip under the pointer in the timeline'
    end
    entry do
      name 'Select Clip Above'
      command 'CMD+Up Arrow'
      notes 'Select the clip above the current timeline selection at the skimmer or playhead location'
    end
    entry do
      name 'Select Clip Below'
      command 'CMD+Down Arrow'
      notes 'Select the clip below the current timeline selection at the skimmer or playhead location'
    end
    entry do
      name 'Select Left Audio Edge'
      command 'SHIFT+['
      notes 'For audio/video clips in expanded view, select the left edge of the audio edit point'
    end
    entry do
      name 'Select Left Edge'
      command '['
      notes 'Select the left edge of the edit point'
    end
    entry do
      name 'Select Left and Right Audio Edit Edges'
      command 'SHIFT+\\'
      notes 'For audio/video clips in expanded view, select the left and right edges of the audio edit point'
    end
    entry do
      name 'Select Left and Right Edit Edges'
      command '\\'
      notes 'Select the left and right edges of the edit point'
    end
    entry do
      name 'Select Left and Right Video Edit Edges'
      command 'CTRL+\\'
      notes 'For audio/video clips in expanded view, select the left and right edges of the video edit point'
    end
    entry do
      name 'Select Left Video Edge'
      command 'CTRL+['
      notes 'For audio/video clips in expanded view, select the left edge of the video edit point'
    end
    entry do
      name 'Select Next Angle'
      command 'CTRL+SHIFT+Right Arrow'
      notes 'Switch to the next angle in the multicam clip'
    end
    entry do
      name 'Select Next Audio Angle'
      command 'OPTION+SHIFT+Right Arrow'
      notes 'Switch to the next audio angle in the multicam clip'
    end
    entry do
      name 'Select Next Clip'
      command 'CMD+Right Arrow'
      notes 'Move the playhead and the selection to the next topmost timeline clip in the same role'
    end
    entry do
      name 'Select Next Pick'
      command 'CTRL+Right Arrow'
      notes 'Select the next clip in the Audition window, making it the audition pick'
    end
    entry do
      name 'Select Next Video Angle'
      command 'CMD+SHIFT+Right Arrow'
      notes 'Switch to the next video angle in the multicam clip'
    end
    entry do
      name 'Select Previous Clip'
      command 'CMD+Left Arrow'
      notes 'Move the playhead and the selection to the previous topmost timeline clip in the same role'
    end
    entry do
      name 'Select Right Audio Edge'
      command 'SHIFT+]'
      notes 'For audio/video clips in expanded view, select the right edge of the audio edit point'
    end
    entry do
      name 'Select Right Edge'
      command ']'
      notes 'Select the right edge of the edit point'
    end
    entry do
      name 'Select Right Video Edge'
      command 'CTRL+]'
      notes 'For audio/video clips in expanded view, select the right edge of the video edit point'
    end
    entry do
      name 'Set Additional Selection End'
      command 'CMD+SHIFT+O'
      notes 'Set an additional range selection end point at the playhead or skimmer location'
    end
    entry do
      name 'Set Additional Selection Start'
      command 'CMD+SHIFT+I'
      notes 'Set an additional range selection start point at the playhead or skimmer location'
    end
    entry do
      name 'Show/Hide Precision Editor'
      command 'CTRL+E'
      notes 'When an edit point is selected, show or hide the precision editor'
    end
    entry do
      name 'Snapping'
      command 'N'
      notes 'Turn snapping on or off'
    end
    entry do
      name 'Solo'
      command 'OPTION+S'
      notes 'Solo the selected items in the timeline'
    end
    entry do
      name 'Source Media: Audio & Video'
      command 'SHIFT+1'
      notes 'Turn on audio/video mode to add the video and audio portion of your selection to the timeline'
    end
    entry do
      name 'Source Media: Audio Only'
      command 'SHIFT+3'
      notes 'Turn on audio-only mode to add the audio portion of your selection to the timeline'
    end
    entry do
      name 'Source Media: Video Only'
      command 'SHIFT+2'
      notes 'Turn on video-only mode to add the video portion of your selection to the timeline'
    end
    entry do
      name 'Split Caption'
      command 'CMD+CTRL+OPTION+C'
      notes 'Replace the selected captions with abutting single-line captions, one for each line of text in the original captions.'
    end
    entry do
      name 'Switch to Viewer Angle 1'
      command 'OPTION+1'
      notes 'Switch the multicam clip to angle 1 of the current bank'
    end
    entry do
      name 'Switch to Viewer Angle 2'
      command 'OPTION+2'
      notes 'Switch the multicam clip to angle 2 of the current bank'
    end
    entry do
      name 'Switch to Viewer Angle 3'
      command 'OPTION+3'
      notes 'Switch the multicam clip to angle 3 of the current bank'
    end
    entry do
      name 'Switch to Viewer Angle 4'
      command 'OPTION+4'
      notes 'Switch the multicam clip to angle 4 of the current bank'
    end
    entry do
      name 'Switch to Viewer Angle 5'
      command 'OPTION+5'
      notes 'Switch the multicam clip to angle 5 of the current bank'
    end
    entry do
      name 'Switch to Viewer Angle 6'
      command 'OPTION+6'
      notes 'Switch the multicam clip to angle 6 of the current bank'
    end
    entry do
      name 'Switch to Viewer Angle 7'
      command 'OPTION+7'
      notes 'Switch the multicam clip to angle 7 of the current bank'
    end
    entry do
      name 'Switch to Viewer Angle 8'
      command 'OPTION+8'
      notes 'Switch the multicam clip to angle 8 of the current bank'
    end
    entry do
      name 'Switch to Viewer Angle 9'
      command 'OPTION+9'
      notes 'Switch the multicam clip to angle 9 of the current bank'
    end
    entry do
      name 'Toggle Storyline Mode'
      command 'G'
      notes 'Turn on or turn off the ability to build storylines when dragging clips in the timeline'
    end
    entry do
      name 'Trim End'
      command 'OPTION+]'
      notes 'Trim the end of the selected or topmost clip to the skimmer or playhead position'
    end
    entry do
      name 'Trim Start'
      command 'OPTION+['
      notes 'Trim the clip start point to the skimmer or playhead position'
    end
    entry do
      name 'Trim to Selection'
      command 'OPTION+\\'
      notes 'Trim clip start and end points to the range selection'
    end
  end

  category do
    id 'Effects'
    entry do
      name 'Add Basic Lower Third'
      command 'CTRL+SHIFT+T'
      notes 'Connect a basic lower-third title to the primary storyline'
    end
    entry do
      name 'Add Basic Title'
      command 'CTRL+T'
      notes 'Connect a basic title to the primary storyline'
    end
    entry do
      name 'Add Default Audio Effect'
      command 'CMD+OPTION+E'
      notes 'Add the default audio effect to the selection'
    end
    entry do
      name 'Add Default Transition'
      command 'CMD+T'
      notes 'Add the default transition to the selection'
    end
    entry do
      name 'Add Default Video Effect'
      command 'OPTION+E'
      notes 'Add the default video effect to the selection'
    end
    entry do
      name 'Color Board: Reset Current Board Controls'
      command 'OPTION+Delete'
      notes 'Reset the controls in the current Color Board pane'
    end
    entry do
      name 'Color Board: Switch to the Color Pane'
      command 'CMD+CTRL+C'
      notes 'Switch to the Color pane in the Color Board'
    end
    entry do
      name 'Color Board: Switch to the Exposure Pane'
      command 'CMD+CTRL+E'
      notes 'Switch to the Exposure pane in the Color Board'
    end
    entry do
      name 'Color Board: Switch to the Saturation Pane'
      command 'CMD+CTRL+S'
      notes 'Switch to the Saturation pane in the Color Board'
    end
    entry do
      name 'Copy Effects'
      command 'CMD+OPTION+C'
      notes 'Copy the selected effects and their settings'
    end
    entry do
      name 'Copy Keyframes'
      command 'OPTION+SHIFT+C'
      notes 'Copy the selected keyframes and their settings'
    end
    entry do
      name 'Cut Keyframes'
      command 'OPTION+SHIFT+X'
      notes 'Cut the selected keyframes and their settings'
    end
    entry do
      name 'Enable/Disable Balance Color'
      command 'CMD+OPTION+B'
      notes 'Turn Balance Color corrections on or off'
    end
    entry do
      name 'Match Audio'
      command 'CMD+SHIFT+M'
      notes 'Match the sound between clips'
    end
    entry do
      name 'Match Color'
      command 'CMD+OPTION+M'
      notes 'Match color between clips'
    end
    entry do
      name 'Next Text'
      command 'OPTION+Tab'
      notes 'Navigate to the next text item'
    end
    entry do
      name 'Paste Attributes'
      command 'CMD+SHIFT+V'
      notes 'Paste selected attributes and their settings to the selection'
    end
    entry do
      name 'Paste Effects'
      command 'CMD+OPTION+V'
      notes 'Paste effects and their settings to the selection'
    end
    entry do
      name 'Paste Keyframes'
      command 'OPTION+SHIFT+V'
      notes 'Paste keyframes and their settings to the selection'
    end
    entry do
      name 'Previous Text'
      command 'OPTION+SHIFT+Tab'
      notes 'Navigate to the previous text item'
    end
    entry do
      name 'Remove Attributes'
      command 'CMD+SHIFT+X'
      notes 'Remove selected attributes from the selection'
    end
    entry do
      name 'Remove Effects'
      command 'CMD+OPTION+X'
      notes 'Remove all effects from the selection'
    end
    entry do
      name 'Retime Editor'
      command 'CMD+R'
      notes 'Show or hide the retime editor'
    end
    entry do
      name 'Retime: Create Normal Speed Segment'
      command 'SHIFT+N'
      notes 'Set the selection to play at normal (100 percent) speed'
    end
    entry do
      name 'Retime: Hold'
      command 'SHIFT+H'
      notes 'Create a 2-second hold segment'
    end
    entry do
      name 'Retime: Reset'
      command 'CMD+OPTION+R'
      notes 'Reset the selection to play forward at normal (100 percent) speed'
    end
    entry do
      name 'Solo Animation'
      command 'CTRL+SHIFT+V'
      notes 'Show one effect at a time in the Video Animation editor'
    end
  end

  category do
    id 'General'
    entry do
      name 'Delete'
      command 'Delete'
      notes 'Delete the timeline selection, reject the browser selection, or remove a through edit'
    end
    entry do
      name 'Find'
      command 'CMD+F'
      notes 'Show or hide the Filter window (in the browser) or the timeline index (in the timeline)'
    end
    entry do
      name 'Go to Event Viewer'
      command 'CMD+OPTION+3'
      notes 'Make the event viewer active'
    end
    entry do
      name 'Import Media'
      command 'CMD+I'
      notes 'Import media from a device, a camera, or an archive'
    end
    entry do
      name 'Library Properties'
      command 'CMD+CTRL+J'
      notes 'Open the Library Properties inspector for the current library'
    end
    entry do
      name 'Move to Trash'
      command 'CMD+Delete'
      notes 'Move the selection to the Finder Trash'
    end
    entry do
      name 'New Project'
      command 'CMD+N'
      notes 'Create a new project'
    end
    entry do
      name 'Project Properties'
      command 'CMD+J'
      notes 'Open the Properties inspector for the current project'
    end
    entry do
      name 'Render All'
      command 'CTRL+SHIFT+R'
      notes 'Start all rendering tasks for the current project'
    end
    entry do
      name 'Render Selection'
      command 'CTRL+R'
      notes 'Start rendering tasks for the selection'
    end
    entry do
      name 'Reveal in Finder'
      command 'CMD+SHIFT+R'
      notes 'Reveal the selected event clip’s source media file in the Finder'
    end
  end

  category do
    id 'Marking'
    entry do
      name 'Add Caption'
      command 'OPTION+C'
      notes 'Add a caption to the active language subrole at the playhead location'
    end
    entry do
      name 'Add Marker'
      command 'M'
      notes 'Add a marker at the location of the skimmer or playhead'
    end
    entry do
      name 'All Clips'
      command 'CTRL+C'
      notes 'Change the browser filter settings to show all clips'
    end
    entry do
      name 'Add Marker and Modify'
      command 'OPTION+M'
      notes 'Add a marker and edit the marker’s text'
    end
    entry do
      name 'Apply Keyword Tag 1'
      command 'CTRL+1'
      notes 'Apply keyword 1 to the selection'
    end
    entry do
      name 'Apply Keyword Tag 2'
      command 'CTRL+2'
      notes 'Apply keyword 2 to the selection'
    end
    entry do
      name 'Apply Keyword Tag 3'
      command 'CTRL+3'
      notes 'Apply keyword 3 to the selection'
    end
    entry do
      name 'Apply Keyword Tag 4'
      command 'CTRL+4'
      notes 'Apply keyword 4 to the selection'
    end
    entry do
      name 'Apply Keyword Tag 5'
      command 'CTRL+5'
      notes 'Apply keyword 5 to the selection'
    end
    entry do
      name 'Apply Keyword Tag 6'
      command 'CTRL+6'
      notes 'Apply keyword 6 to the selection'
    end
    entry do
      name 'Apply Keyword Tag 7'
      command 'CTRL+7'
      notes 'Apply keyword 7 to the selection'
    end
    entry do
      name 'Apply Keyword Tag 8'
      command 'CTRL+8'
      notes 'Apply keyword 8 to the selection'
    end
    entry do
      name 'Apply Keyword Tag 9'
      command 'CTRL+9'
      notes 'Apply keyword 9 to the selection'
    end
    entry do
      name 'Clear Selected Ranges'
      command 'OPTION+X'
      notes 'Clear the range selection'
    end
    entry do
      name 'Clear Range End'
      command 'OPTION+O'
      notes 'Clear the range’s end point'
    end
    entry do
      name 'Clear Range Start'
      command 'OPTION+I'
      notes 'Clear the range’s start point'
    end
    entry do
      name 'Delete Marker'
      command 'CTRL+M'
      notes 'Delete the selected marker'
    end
    entry do
      name 'Delete Markers in Selection'
      command 'CTRL+SHIFT+M'
      notes 'Delete all of the markers in the selection'
    end
    entry do
      name 'Deselect All'
      command 'CMD+SHIFT+A'
      notes 'Deselect all selected items'
    end
    entry do
      name 'Edit Caption'
      command 'CTRL+SHIFT+C'
      notes 'Open the selected caption in the caption editor'
    end
    entry do
      name 'Favorite'
      command 'F'
      notes 'Rate the browser selection as favorite'
    end
    entry do
      name 'Favorites'
      command 'CTRL+F'
      notes 'Change the browser filter settings to show favorites'
    end
    entry do
      name 'Hide Rejected'
      command 'CTRL+H'
      notes 'Change the browser filter settings to hide rejected clips'
    end
    entry do
      name 'New Keyword Collection'
      command 'CMD+SHIFT+K'
      notes 'Create a new Keyword Collection'
    end
    entry do
      name 'New Smart Collection'
      command 'CMD+OPTION+N'
      notes 'Create a new Smart Collection'
    end
    entry do
      name 'Range Selection Tool'
      command 'R'
      notes 'Make the Range Selection tool active'
    end
    entry do
      name 'Reject'
      command 'Delete'
      notes 'Mark the current selection in the browser as rejectedNote: The Delete key removes selected items if the timeline is active instead of the browser.'
    end
    entry do
      name 'Rejected'
      command 'CTRL+Delete'
      notes 'Change the browser filter settings to show rejected clips'
    end
    entry do
      name 'Remove All Keywords From Selection'
      command 'CTRL+0'
      notes 'Remove all keywords from the browser selection'
    end
    entry do
      name 'Roles: Apply Dialogue Role'
      command 'CTRL+OPTION+D'
      notes 'Apply Dialogue subroles to the selected clip’s components'
    end
    entry do
      name 'Roles: Apply Effects Role'
      command 'CTRL+OPTION+E'
      notes 'Apply Effects subroles to the selected clip’s components'
    end
    entry do
      name 'Roles: Apply Music Role'
      command 'CTRL+OPTION+M'
      notes 'Apply Music subroles to the selected clip’s components'
    end
    entry do
      name 'Roles: Apply Titles Role'
      command 'CTRL+OPTION+T'
      notes 'Apply the Titles role to the selected clip'
    end
    entry do
      name 'Roles: Apply Video Role'
      command 'CTRL+OPTION+V'
      notes 'Apply the Video role to the selected clip'
    end
    entry do
      name 'Select All'
      command 'CMD+A'
      notes 'Select all clips'
    end
    entry do
      name 'Select Clip Range'
      command 'X'
      notes 'Set the range selection to match the boundaries of the clip below the skimmer or playhead'
    end
    entry do
      name 'Set Additional Range End'
      command 'CMD+SHIFT+O'
      notes 'Set an additional range selection end point at the playhead or skimmer location'
    end
    entry do
      name 'Set Additional Range Start'
      command 'CMD+SHIFT+I'
      notes 'Set an additional range selection start point at the playhead or skimmer location'
    end
    entry do
      name 'Set Range End'
      command 'O'
      notes 'Set the end point for the range'
    end
    entry do
      name 'Set Range End'
      command 'CTRL+O'
      notes 'Set the end point for the range while editing a text field'
    end
    entry do
      name 'Set Range Start'
      command 'I'
      notes 'Set the start point for the range'
    end
    entry do
      name 'Set Range Start'
      command 'CTRL+I'
      notes 'Set the start point for the range while editing a text field'
    end
    entry do
      name 'Unrate'
      command 'U'
      notes 'Remove ratings from the selection'
    end
  end

  category do
    id 'Organization'
    entry do
      name 'New Event'
      command 'OPTION+N'
      notes 'Create a new event'
    end
    entry do
      name 'New Folder'
      command 'CMD+SHIFT+N'
      notes 'Create a new folder'
    end
    entry do
      name 'Reveal in Browser'
      command 'SHIFT+F'
      notes 'Reveal the selected clip in the browser'
    end
    entry do
      name 'Reveal Project in Browser'
      command 'CMD+OPTION+SHIFT+F'
      notes 'Reveal the open project in the browser'
    end
    entry do
      name 'Synchronize Clips'
      command 'CMD+OPTION+G'
      notes 'Sync the selected event clips'
    end
  end

  category do
    id 'Playback and navigation'
    entry do
      name 'Audio Skimming'
      command 'SHIFT+S'
      notes 'Turn audio skimming on or off'
    end
    entry do
      name 'Audition: Preview'
      command 'CMD+CTRL+Y'
      notes 'Play the pick in context in the timeline'
    end
    entry do
      name 'Clip Skimming'
      command 'CMD+OPTION+S'
      notes 'Turn clip skimming on or off'
    end
    entry do
      name 'Cut/Switch Multicam Audio Only'
      command 'OPTION+SHIFT+3'
      notes 'Turn on audio-only mode for multicam cutting and switching'
    end
    entry do
      name 'Cut/Switch Multicam Audio and Video'
      command 'OPTION+SHIFT+1'
      notes 'Turn on audio/video mode for multicam cutting and switching'
    end
    entry do
      name 'Cut/Switch Multicam Video Only'
      command 'OPTION+SHIFT+2'
      notes 'Turn on video-only mode for multicam cutting and switching'
    end
    entry do
      name 'Down'
      command 'Down Arrow'
      notes 'Go to the next item (in the browser) or the next edit point (in the timeline)'
    end
    entry do
      name 'Down'
      command 'CTRL+Down Arrow'
      notes 'While editing a text field, go to the next item (in the browser) or the next edit point (in the timeline)'
    end
    entry do
      name 'Go Back 10 Frames'
      command 'SHIFT+Left Arrow'
      notes 'Move the playhead back 10 frames'
    end
    entry do
      name 'Go Forward 10 Frames'
      command 'SHIFT+Right Arrow'
      notes 'Move the playhead forward 10 frames'
    end
    entry do
      name 'Go to Beginning'
      command 'Home key'
      notes 'Move the playhead to the beginning of the timeline or the first clip in the browser'
    end
    entry do
      name 'Go to End'
      command 'End key'
      notes 'Move the playhead to the end of the timeline or to the last clip in the browser'
    end
    entry do
      name 'Go to Next Bank'
      command 'OPTION+SHIFT+’'
      notes 'Display the next bank of angles in the current multicam clip'
    end
    entry do
      name 'Go to Next Edit'
      command '’'
      notes 'Move the playhead to the next edit point in the timeline'
    end
    entry do
      name 'Go to Next Field'
      command 'OPTION+Right Arrow'
      notes 'Move the playhead to the next field in an interlaced clip'
    end
    entry do
      name 'Go to Next Frame'
      command 'Right Arrow'
      notes 'Move the playhead to the next frame'
    end
    entry do
      name 'Go to Next Subframe'
      command 'OPTION+Right Arrow'
      notes 'Move the playhead to the next audio subframe'
    end
    entry do
      name 'Go to Previous Bank'
      command 'OPTION+SHIFT+;'
      notes 'Display the previous bank of angles in the current multicam clip'
    end
    entry do
      name 'Go to Previous Edit'
      command ';'
      notes 'Move the playhead to the previous edit point in the timeline'
    end
    entry do
      name 'Go to Previous Field'
      command 'OPTION+Left Arrow'
      notes 'Move the playhead to the previous field in an interlaced clip'
    end
    entry do
      name 'Go to Previous Frame'
      command 'Left Arrow'
      notes 'Move the playhead to the previous frame'
    end
    entry do
      name 'Go to Previous Subframe'
      command 'OPTION+Left Arrow'
      notes 'Move the playhead to the previous audio subframe'
    end
    entry do
      name 'Go to Range End'
      command 'SHIFT+O'
      notes 'Move the playhead to the end of the range selection'
    end
    entry do
      name 'Go to Range Start'
      command 'SHIFT+I'
      notes 'Move the playhead to the beginning of the range selection'
    end
    entry do
      name 'Look Clockwise'
      command 'CMD+CTRL+OPTION+Right Bracket'
      notes 'Roll the 360° viewer clockwise'
    end
    entry do
      name 'Look Counterclockwise'
      command 'CMD+CTRL+OPTION+Left Bracket'
      notes 'Roll the 360° viewer counterclockwise'
    end
    entry do
      name 'Look Down'
      command 'CMD+CTRL+OPTION+Down Arrow'
      notes 'Tilt the 360° viewer down'
    end
    entry do
      name 'Look Left'
      command 'CMD+CTRL+OPTION+Left Arrow'
      notes 'Pan the 360° viewer to the left'
    end
    entry do
      name 'Look Right'
      command 'CMD+CTRL+OPTION+Right Arrow'
      notes 'Pan the 360° viewer to the right'
    end
    entry do
      name 'Look Up'
      command 'CMD+CTRL+OPTION+Up Arrow'
      notes 'Pan the 360° viewer up'
    end
    entry do
      name 'Loop Playback'
      command 'CMD+L'
      notes 'Turn looped playback on or off'
    end
    entry do
      name 'Mirror VR Headset'
      command 'CMD+CTRL+OPTION+9'
      notes 'Mirror the display of the connected VR headset in the 360° viewer'
    end
    entry do
      name 'Monitor Audio'
      command 'SHIFT+A'
      notes 'Turn on or turn off audio monitoring for the angle being skimmed'
    end
    entry do
      name 'Negative Timecode Entry'
      command '-'
      notes 'Enter a negative timecode value to move the playhead back, move a clip earlier, or trim a range or clip, depending on your selection'
    end
    entry do
      name 'Next Clip'
      command 'CMD+CTRL+Right Arrow'
      notes 'Go to the next item (in the browser) or the next edit point (in the timeline)'
    end
    entry do
      name 'Next Marker'
      command 'CTRL+’'
      notes 'Move the playhead to the next marker'
    end
    entry do
      name 'Output to VR Headset'
      command 'CMD+CTRL+OPTION+7'
      notes 'Send 360° video to the connected VR headset'
    end
    entry do
      name 'Play Around'
      command 'SHIFT+Question Mark (?)'
      notes 'Play around the playhead position'
    end
    entry do
      name 'Play Forward'
      command 'L'
      notes 'Play forward (press L multiple times to increase the playback speed)'
    end
    entry do
      name 'Play from Playhead'
      command 'OPTION+Space bar'
      notes 'Play from the playhead position'
    end
    entry do
      name 'Play Full Screen'
      command 'CMD+SHIFT+F'
      notes 'Play full screen from the skimmer or playhead position'
    end
    entry do
      name 'Play Reverse'
      command 'J'
      notes 'Play in reverse (press J multiple times to increase the reverse playback speed)'
    end
    entry do
      name 'Play Reverse'
      command 'CTRL+J'
      notes 'Play in reverse while editing a text field (press J multiple times to increase the reverse playback speed)'
    end
    entry do
      name 'Play Reverse'
      command 'SHIFT+Space bar'
      notes 'Play in reverse'
    end
    entry do
      name 'Play Selection'
      command '/'
      notes 'Play the selection'
    end
    entry do
      name 'Play to End'
      command 'CTRL+SHIFT+O'
      notes 'Play from the playhead to the end of the selection'
    end
    entry do
      name 'Play/Pause'
      command 'Space bar'
      notes 'Start or pause playback'
    end
    entry do
      name 'Play/Pause'
      command 'CTRL+Space bar'
      notes 'Start or pause playback while editing a text field'
    end
    entry do
      name 'Positive Timecode Entry'
      command '='
      notes 'Enter a positive timecode value to move the playhead forward, move a clip later, or trim a range or clip, depending on your selection'
    end
    entry do
      name 'Previous Clip'
      command 'CMD+CTRL+Left Arrow'
      notes 'Go to the previous item (in the browser) or the previous edit point (in the timeline)'
    end
    entry do
      name 'Previous Marker'
      command 'CTRL+;'
      notes 'Move the playhead to the previous marker'
    end
    entry do
      name 'Set Monitoring Angle'
      command 'SHIFT+V'
      notes 'Set the angle being skimmed as the monitoring angle'
    end
    entry do
      name 'Skimming'
      command 'S'
      notes 'Turn skimming on or off'
    end
    entry do
      name 'Start/Stop Voiceover Recording'
      command 'OPTION+SHIFT+A'
      notes 'Start or stop recording audio from the Record Voiceover window'
    end
    entry do
      name 'Stop'
      command 'K'
      notes 'Stop playback'
    end
    entry do
      name 'Stop'
      command 'CTRL+K'
      notes 'Stop playback while editing a text field'
    end
    entry do
      name 'Timeline History Back'
      command 'CMD+['
      notes 'Go back one level in the timeline history'
    end
    entry do
      name 'Timeline History Forward'
      command 'CMD+]'
      notes 'Go forward one level in the timeline history'
    end
    entry do
      name 'Up'
      command 'Up Arrow'
      notes 'Go to the previous item (in the browser) or the previous edit point (in the timeline)'
    end
    entry do
      name 'Up'
      command 'CTRL+Up Arrow'
      notes 'While editing a text field, go to the previous item (in the browser) or the previous edit point (in the timeline)'
    end
  end

  category do
    id 'Share and tools'
    entry do
      name 'Share to Default Destination'
      command 'CMD+E'
      notes 'Share the selected project or clip using the default destination'
    end
    entry do
      name 'Select (Arrow) Tool'
      command 'A'
      notes 'Make the Select tool active'
    end
    entry do
      name 'Blade Tool'
      command 'B'
      notes 'Make the Blade tool active'
    end
    entry do
      name 'Crop Tool'
      command 'SHIFT+C'
      notes 'Make the Crop tool active and display onscreen controls for the selected clip or the topmost clip under the playhead'
    end
    entry do
      name 'Distort Tool'
      command 'OPTION+D'
      notes 'Make the Distort tool active and display onscreen controls for the selected clip or the topmost clip under the playhead'
    end
    entry do
      name 'Hand Tool'
      command 'H'
      notes 'Make the Hand tool active'
    end
    entry do
      name 'Position Tool'
      command 'P'
      notes 'Make the Position tool active'
    end
    entry do
      name 'Transform Tool'
      command 'SHIFT+T'
      notes 'Make the Transform tool active and display onscreen controls for the selected clip or the topmost clip under the playhead'
    end
    entry do
      name 'Trim Tool'
      command 'T'
      notes 'Make the Trim tool active'
    end
    entry do
      name 'Zoom Tool'
      command 'Z'
      notes 'Make the Zoom tool active'
    end
  end

  category do
    id 'View'
    entry do
      name 'Clip Appearance: Clip Labels Only'
      command 'CTRL+OPTION+6'
      notes 'Depending on the clip name setting, display timeline clips with clip names, role names, or active angle names only'
    end
    entry do
      name 'Clip Appearance: Decrease Waveform Size'
      command 'CTRL+OPTION+Down Arrow'
      notes 'Decrease the size of audio waveforms for timeline clips'
    end
    entry do
      name 'Clip Appearance: Filmstrips Only'
      command 'CTRL+OPTION+5'
      notes 'Display timeline clips with large filmstrips only'
    end
    entry do
      name 'Clip Appearance: Increase Waveform Size'
      command 'CTRL+OPTION+Up Arrow'
      notes 'Increase the size of audio waveforms for timeline clips'
    end
    entry do
      name 'Clip Appearance: Large Filmstrips'
      command 'CTRL+OPTION+4'
      notes 'Display timeline clips with small audio waveforms and large filmstrips'
    end
    entry do
      name 'Clip Appearance: Large Waveforms'
      command 'CTRL+OPTION+2'
      notes 'Display timeline clips with large audio waveforms and small filmstrips'
    end
    entry do
      name 'Clip Appearance: Waveforms and Filmstrips'
      command 'CTRL+OPTION+3'
      notes 'Display timeline clips with audio waveforms and video filmstrips of equal size'
    end
    entry do
      name 'Clip Appearance: Waveforms Only'
      command 'CTRL+OPTION+1'
      notes 'Display timeline clips with large audio waveforms only'
    end
    entry do
      name 'Decrease Clip Height'
      command 'CMD+SHIFT+-'
      notes 'Decrease the browser clip height'
    end
    entry do
      name 'Increase Clip Height'
      command 'CMD+SHIFT+='
      notes 'Increase the browser clip height'
    end
    entry do
      name 'Show Fewer Filmstrip Frames'
      command 'CMD+SHIFT+,'
      notes 'Show fewer filmstrip frames in browser clips'
    end
    entry do
      name 'Show/Hide Audio Animation'
      command 'CTRL+A'
      notes 'Show or hide the Audio Animation editor for the selected clips or components'
    end
    entry do
      name 'Show/Hide Skimmer Info'
      command 'CTRL+Y'
      notes 'Show or hide clip information when skimming in the browser'
    end
    entry do
      name 'Show/Hide Video Animation'
      command 'CTRL+V'
      notes 'Show or hide the Video Animation editor for the selected timeline clips'
    end
    entry do
      name 'Show More Filmstrip Frames'
      command 'CMD+SHIFT+.'
      notes 'Show more filmstrip frames in browser clips'
    end
    entry do
      name 'Show One Frame per Filmstrip'
      command 'CMD+OPTION+SHIFT+,'
      notes 'Show one frame per filmstrip'
    end
    entry do
      name 'Toggle Filmstrip/List View'
      command 'CMD+OPTION+2'
      notes 'Switch the browser between filmstrip view and list view'
    end
    entry do
      name 'View Clip Names'
      command 'OPTION+SHIFT+N'
      notes 'Show or hide clip names in the browser'
    end
    entry do
      name 'Zoom In'
      command 'CMD+Plus Sign (+)'
      notes 'Zoom in to the browser, viewer, or timeline'
    end
    entry do
      name 'Zoom Out'
      command 'CMD+Minus Sign (–)'
      notes 'Zoom out of the browser, viewer, or timeline'
    end
    entry do
      name 'Zoom to Fit'
      command 'SHIFT+Z'
      notes 'Zoom the contents to fit the size of the browser, viewer, or timeline'
    end
    entry do
      name 'Zoom to Samples'
      command 'CTRL+Z'
      notes 'Turn zooming in to audio samples on or off'
    end
  end

  category do
    id 'Windows'
    entry do
      name 'Background Tasks'
      command 'CMD+9'
      notes 'Show or hide the Background Tasks window'
    end
    entry do
      name 'Go to Audio Enhancements'
      command 'CMD+8'
      notes 'Make the Audio Enhancements inspector active'
    end
    entry do
      name 'Go to Color Board'
      command 'CMD+6'
      notes 'Make the Color Board active'
    end
    entry do
      name 'Go to Browser'
      command 'CMD+1'
      notes 'Make the browser active'
    end
    entry do
      name 'Go to Inspector'
      command 'CMD+OPTION+4'
      notes 'Make the current inspector active'
    end
    entry do
      name 'Go to Timeline'
      command 'CMD+2'
      notes 'Make the timeline active'
    end
    entry do
      name 'Go to Viewer'
      command 'CMD+3'
      notes 'Make the viewer active'
    end
    entry do
      name 'Next Tab'
      command 'CTRL+Tab'
      notes 'Go to the next pane in the inspector or the Color Board'
    end
    entry do
      name 'Previous Tab'
      command 'CTRL+SHIFT+Tab'
      notes 'Go to the previous pane in the inspector or the Color Board'
    end
    entry do
      name 'Record Voiceover'
      command 'CMD+OPTION+8'
      notes 'Show or hide the Record Voiceover window'
    end
    entry do
      name 'Show Histogram'
      command 'CMD+CTRL+H'
      notes 'Show the histogram in the viewer'
    end
    entry do
      name 'Show Vectorscope'
      command 'CMD+CTRL+V'
      notes 'Show the vectorscope in the viewer'
    end
    entry do
      name 'Show Video Waveform'
      command 'CMD+CTRL+W'
      notes 'Show the waveform monitor in the viewer'
    end
    entry do
      name 'Show/Hide Angles'
      command 'CMD+SHIFT+7'
      notes 'Show or hide the angle viewer'
    end
    entry do
      name 'Show/Hide Audio Meters'
      command 'CMD+SHIFT+8'
      notes 'Show or hide the audio meters'
    end
    entry do
      name 'Show/Hide Browser'
      command 'CMD+CTRL+1'
      notes 'Show or hide the browser'
    end
    entry do
      name 'Show/Hide Comparison Viewer'
      command 'CMD+CTRL+6'
      notes 'Show or hide the comparison viewer'
    end
    entry do
      name 'Show/Hide Effects Browser'
      command 'CMD+5'
      notes 'Show or hide the Effects browser'
    end
    entry do
      name 'Show/Hide Transitions Browser'
      command 'CMD+CTRL+5'
      notes 'Show or hide the Transitions browser'
    end
    entry do
      name 'Show/Hide Event Viewer'
      command 'CMD+CTRL+3'
      notes 'Show or hide the event viewer'
    end
    entry do
      name 'Show/Hide Inspector'
      command 'CMD+4'
      notes 'Show or hide the inspector'
    end
    entry do
      name 'Show/Hide Keyword Editor'
      command 'CMD+K'
      notes 'Show or hide the keyword editor'
    end
    entry do
      name 'Show/Hide Libraries Sidebar'
      command 'CMD+1'
      notes 'Show or hide the Libraries sidebar'
    end
    entry do
      name 'Show/Hide Photos and Audio Sidebar'
      command 'CMD+SHIFT+1'
      notes 'Show or hide the Photos and Audio sidebar'
    end
    entry do
      name 'Show/Hide Sidebar'
      command 'CMD+`'
      notes 'Show or hide the sidebar'
    end
    entry do
      name 'Show/Hide 360° Viewer'
      command 'CMD+OPTION+7'
      notes 'Show or hide the 360° viewer'
    end
    entry do
      name 'Show/Hide Timeline'
      command 'CMD+CTRL+2'
      notes 'Show or hide the timeline'
    end
    entry do
      name 'Show/Hide Timeline Index'
      command 'CMD+SHIFT+2'
      notes 'Show or hide the timeline index for the open project'
    end
    entry do
      name 'Show/Hide Titles and Generators Sidebar'
      command 'CMD+OPTION+1'
      notes 'Show or hide the Titles and Generators sidebar'
    end
    entry do
      name 'Show/Hide Video Scopes'
      command 'CMD+7'
      notes 'Show or hide the video scopes in the viewer'
    end
    entry do
      name 'Toggle Inspector Height'
      command 'CMD+CTRL+4'
      notes 'Switch between the half-height view and full-height view in the inspector'
    end
  end
end
